#include "theme_manager.h"

QStringList ThemeManager::availableThemes() {
    return {
        "blender",
        "pie",
        "wheel",
        "shotgun",
        "semicircle",
        "cyber-fan",
        "cyberpunk",
        "nord",
        "catppuccin",
        "dracula",
        "tokyo-night",
        "glassmorphism",
        "apple-glass",
        "apple-glass-light",
        "visionos",
        "apple-glass-pie",
        "apple-lens",
        "apple-lens-light",
        "visionos-lens",
        "liquid-glass",
        "liquid-glass-light",
        "monochrome",
        "light"
    };
}

QVariantMap ThemeManager::resolveStyle(const QString &themeName, const QVariantMap &customOverrides) {
    QVariantMap style;

    // ── Default Theme (Blender Slate & Orange) ─────────────────────────────────
    style["backgroundColor"]      = "#000000";
    style["backgroundOpacity"]    = 0.38;
    style["pillColor"]            = "#1a1a20";
    style["pillHoverColor"]       = "#2b2b36";
    style["pillBorderColor"]      = "#383842";
    style["pillBorderHoverColor"] = "#e67e22";
    style["pillSubmenuColor"]     = "#18151f";
    style["pillSubmenuHoverColor"]= "#2a2438";
    style["pillSubmenuBorder"]    = "#4a3060";
    style["pillSubmenuBorderHover"] = "#a855f7";
    style["textColor"]            = "#d0d0d5";
    style["textHoverColor"]       = "#ffffff";
    style["accentColor"]          = "#e67e22";
    style["iconColor"]            = "#a0a0ab";
    style["iconHoverColor"]       = "#f39c12";
    style["submenuAccent"]        = "#c084fc";
    style["centerColor"]          = "#18181c";
    style["centerBorder"]         = "#4a4a56";
    style["centerBorderHover"]    = "#e67e22";
    style["centerDotColor"]       = "#808090";
    style["centerDotHoverColor"]  = "#e67e22";
    style["guideRingColor"]       = "#ffffff";
    style["guideRingOpacity"]     = 0.07;
    style["breadcrumbColor"]      = "#606070";
    style["fontFamily"]           = "Sans";
    style["fontSize"]             = 13;
    style["iconSize"]             = 22;
    style["radiusDistance"]       = 185;
    style["pillHeight"]           = 42;
    style["pillRadius"]           = 21; // 21 = full rounded pill
    style["borderWidth"]          = 1;
    style["borderHoverWidth"]     = 2;
    style["showGuideRing"]        = true;
    style["showPointerLine"]      = true;
    style["showBreadcrumbs"]      = true;

    QString name = themeName.toLower().trimmed();

    if (name == "pie" || name == "wheel") {
        style["layout"]               = "pie";
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.50;
        style["pieBackgroundColor"]   = "#14141d";
        style["pieBackgroundOpacity"] = 0.95;
        style["pieOuterBorderColor"]  = "#5a5a72";
        style["pieOuterBorderWidth"]  = 3;
        style["innerRadius"]          = 65;
        style["outerRadius"]          = 230;
        style["delimiterWidth"]       = 2;
        style["delimiterColor"]       = "#383848";
        style["pieSliceColor"]        = "#1e1e2a";
        style["pieSliceHoverColor"]   = "#323246";
        style["pieSliceSubmenuColor"] = "#1e1e2a";
        style["pieSliceSubmenuHoverColor"] = "#323246";
        style["accentColor"]          = "#e67e22";
        style["submenuAccent"]        = "#c084fc";
        style["textColor"]            = "#e2e2ec";
        style["textHoverColor"]       = "#ffffff";
        style["fontSize"]             = 15;
        style["iconSize"]             = 26;
        style["centerColor"]          = "#111116";
        style["centerBorderColor"]     = "#5a5a72";
        style["centerBorderHoverColor"]= "#e67e22";
        style["centerBorderWidth"]    = 3;
        style["centerDotColor"]       = "#808090";
        style["centerDotHoverColor"]  = "#e67e22";
        style["showCenterArc"]        = true;
        style["centerArcAngle"]       = 90;
        style["centerArcColor"]       = "#3b82f6";
        style["centerArcWidth"]       = 4;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "blender") {
        style["layout"]               = "pie";
        style["centerLayout"]         = "torus";
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0;
        style["pieBackgroundColor"]   = "#000000";
        style["pieBackgroundOpacity"] = 0.15;
        style["pieOuterBorderColor"]  = "transparent";
        style["pieOuterBorderWidth"]  = 0;
        style["innerRadius"]          = 50;
        style["outerRadius"]          = 220;
        style["delimiterWidth"]       = 0;
        style["delimiterColor"]       = "transparent";
        style["pieSliceColor"]        = "transparent";
        style["pieSliceHoverColor"]   = "transparent";
        style["pieSliceSubmenuColor"] = "transparent";
        style["pieSliceSubmenuHoverColor"] = "transparent";
        style["accentColor"]          = "#3b82f6";
        style["submenuAccent"]        = "#60a5fa";
        style["textColor"]            = "#cfcfcf";
        style["textHoverColor"]       = "#ffffff";
        style["fontSize"]             = 14;
        style["iconSize"]             = 22;
        style["torusRadius"]          = 26;
        style["centerTorusThickness"] = 8;
        style["centerTorusColor"]     = "#383838";
        style["centerColor"]          = "transparent";
        style["centerBorderColor"]     = "transparent";
        style["centerBorderHoverColor"]= "transparent";
        style["centerBorderWidth"]    = 0;
        style["centerDotColor"]       = "#808080";
        style["centerDotHoverColor"]  = "#3b82f6";
        style["showCenterArc"]        = true;
        style["centerArcAngle"]       = 90;
        style["centerArcColor"]       = "#3b82f6";
        style["centerArcWidth"]       = 8;
        style["highlightOptionRect"]  = true;
        style["optionRectColor"]       = "#222226";
        style["optionRectHoverColor"] = "#2b5b88";
        style["optionRectBorder"]     = "#333338";
        style["optionRectHoverBorder"]= "#3b82f6";
        style["optionRectRadius"]     = 6;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "shotgun") {
        style["backgroundColor"]      = "#0b0402";
        style["backgroundOpacity"]    = 0.50;
        style["pillColor"]            = "#1c0c06";
        style["pillHoverColor"]       = "#361608";
        style["pillBorderColor"]      = "#54200a";
        style["pillBorderHoverColor"] = "#ff4400";
        style["textColor"]            = "#ffaa88";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#ff4400";
        style["iconColor"]            = "#ff5500";
        style["iconHoverColor"]       = "#ffaa00";
        style["centerColor"]          = "#1c0c06";
        style["centerBorder"]         = "#54200a";
        style["centerBorderHover"]    = "#ff4400";
        style["centerDotColor"]       = "#ff5500";
        style["centerDotHoverColor"]  = "#ffaa00";
        style["layout"]               = "shotgun";
        style["startAngle"]           = -150.0;
        style["spreadAngle"]          = 120.0;
        style["pillRadius"]           = 6;
        style["radiusDistance"]       = 170;
        style["showGuideRing"]        = false;
    } else if (name == "semicircle") {
        style["layout"]               = "semicircle";
        style["startAngle"]           = -180.0;
        style["spreadAngle"]          = 180.0;
        style["radiusDistance"]       = 190;
    } else if (name == "cyber-fan") {
        style["layout"]               = "arc-right";
        style["startAngle"]           = -45.0;
        style["spreadAngle"]          = 90.0;
        style["accentColor"]          = "#00f0ff";
        style["pillBorderHoverColor"] = "#ff007f";
        style["radiusDistance"]       = 200;
    } else if (name == "cyberpunk") {
        style["backgroundColor"]      = "#0a0412";
        style["backgroundOpacity"]    = 0.55;
        style["pillColor"]            = "#120924";
        style["pillHoverColor"]       = "#241042";
        style["pillBorderColor"]      = "#00f0ff";
        style["pillBorderHoverColor"] = "#ff007f";
        style["pillSubmenuColor"]     = "#1a0826";
        style["pillSubmenuHoverColor"]= "#380d52";
        style["pillSubmenuBorder"]    = "#bd00ff";
        style["pillSubmenuBorderHover"] = "#00ffff";
        style["textColor"]            = "#00f0ff";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#ff007f";
        style["iconColor"]            = "#ff007f";
        style["iconHoverColor"]       = "#00f0ff";
        style["submenuAccent"]        = "#bd00ff";
        style["centerColor"]          = "#120924";
        style["centerBorder"]         = "#00f0ff";
        style["centerBorderHover"]    = "#ff007f";
        style["centerDotColor"]       = "#00f0ff";
        style["centerDotHoverColor"]  = "#ff007f";
        style["guideRingColor"]       = "#ff007f";
        style["guideRingOpacity"]     = 0.15;
        style["breadcrumbColor"]      = "#bd00ff";
    } else if (name == "nord") {
        style["backgroundColor"]      = "#2e3440";
        style["backgroundOpacity"]    = 0.45;
        style["pillColor"]            = "#3b4252";
        style["pillHoverColor"]       = "#434c5e";
        style["pillBorderColor"]      = "#4c566a";
        style["pillBorderHoverColor"] = "#88c0d0";
        style["pillSubmenuColor"]     = "#2e3440";
        style["pillSubmenuHoverColor"]= "#3b4252";
        style["pillSubmenuBorder"]    = "#5e81ac";
        style["pillSubmenuBorderHover"] = "#81a1c1";
        style["textColor"]            = "#e5e9f0";
        style["textHoverColor"]       = "#eceff4";
        style["accentColor"]          = "#88c0d0";
        style["iconColor"]            = "#81a1c1";
        style["iconHoverColor"]       = "#88c0d0";
        style["submenuAccent"]        = "#b48ead";
        style["centerColor"]          = "#2e3440";
        style["centerBorder"]         = "#4c566a";
        style["centerBorderHover"]    = "#88c0d0";
        style["centerDotColor"]       = "#d8dee9";
        style["centerDotHoverColor"]  = "#88c0d0";
        style["guideRingColor"]       = "#88c0d0";
        style["guideRingOpacity"]     = 0.10;
        style["breadcrumbColor"]      = "#d8dee9";
    } else if (name == "catppuccin") {
        style["backgroundColor"]      = "#11111b";
        style["backgroundOpacity"]    = 0.45;
        style["pillColor"]            = "#1e1e2e";
        style["pillHoverColor"]       = "#313244";
        style["pillBorderColor"]      = "#45475a";
        style["pillBorderHoverColor"] = "#cba6f7";
        style["pillSubmenuColor"]     = "#181825";
        style["pillSubmenuHoverColor"]= "#313244";
        style["pillSubmenuBorder"]    = "#585b70";
        style["pillSubmenuBorderHover"] = "#f5c2e7";
        style["textColor"]            = "#cdd6f4";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#cba6f7";
        style["iconColor"]            = "#89b4fa";
        style["iconHoverColor"]       = "#f9e2af";
        style["submenuAccent"]        = "#f5c2e7";
        style["centerColor"]          = "#181825";
        style["centerBorder"]         = "#45475a";
        style["centerBorderHover"]    = "#cba6f7";
        style["centerDotColor"]       = "#a6adc8";
        style["centerDotHoverColor"]  = "#cba6f7";
        style["guideRingColor"]       = "#cba6f7";
        style["guideRingOpacity"]     = 0.10;
        style["breadcrumbColor"]      = "#a6adc8";
    } else if (name == "dracula") {
        style["backgroundColor"]      = "#282a36";
        style["backgroundOpacity"]    = 0.50;
        style["pillColor"]            = "#44475a";
        style["pillHoverColor"]       = "#6272a4";
        style["pillBorderColor"]      = "#6272a4";
        style["pillBorderHoverColor"] = "#ff79c6";
        style["pillSubmenuColor"]     = "#343746";
        style["pillSubmenuHoverColor"]= "#44475a";
        style["pillSubmenuBorder"]    = "#bd93f9";
        style["pillSubmenuBorderHover"] = "#ff79c6";
        style["textColor"]            = "#f8f8f2";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#ff79c6";
        style["iconColor"]            = "#8be9fd";
        style["iconHoverColor"]       = "#50fa7b";
        style["submenuAccent"]        = "#bd93f9";
        style["centerColor"]          = "#282a36";
        style["centerBorder"]         = "#6272a4";
        style["centerBorderHover"]    = "#ff79c6";
        style["centerDotColor"]       = "#f8f8f2";
        style["centerDotHoverColor"]  = "#ff79c6";
        style["guideRingColor"]       = "#bd93f9";
        style["guideRingOpacity"]     = 0.12;
        style["breadcrumbColor"]      = "#bd93f9";
    } else if (name == "tokyo-night") {
        style["backgroundColor"]      = "#1a1b26";
        style["backgroundOpacity"]    = 0.50;
        style["pillColor"]            = "#24283b";
        style["pillHoverColor"]       = "#414868";
        style["pillBorderColor"]      = "#565f89";
        style["pillBorderHoverColor"] = "#7aa2f7";
        style["pillSubmenuColor"]     = "#1f2335";
        style["pillSubmenuHoverColor"]= "#3b4261";
        style["pillSubmenuBorder"]    = "#bb9af7";
        style["pillSubmenuBorderHover"] = "#7dcfff";
        style["textColor"]            = "#c0caf5";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#7aa2f7";
        style["iconColor"]            = "#7dcfff";
        style["iconHoverColor"]       = "#e0af68";
        style["submenuAccent"]        = "#bb9af7";
        style["centerColor"]          = "#16161e";
        style["centerBorder"]         = "#565f89";
        style["centerBorderHover"]    = "#7aa2f7";
        style["centerDotColor"]       = "#a9b1d6";
        style["centerDotHoverColor"]  = "#7aa2f7";
        style["guideRingColor"]       = "#7aa2f7";
        style["guideRingOpacity"]     = 0.12;
        style["breadcrumbColor"]      = "#9aa5ce";
    } else if (name == "glassmorphism") {
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0;
        style["pillColor"]            = "#35ffffff"; // 21% white translucent
        style["pillHoverColor"]       = "#55ffffff"; // 33% white translucent
        style["pillBorderColor"]      = "#45ffffff";
        style["pillBorderHoverColor"] = "#99ffffff";
        style["pillSubmenuColor"]     = "#28ffffff";
        style["pillSubmenuHoverColor"]= "#48ffffff";
        style["pillSubmenuBorder"]    = "#55ffffff";
        style["pillSubmenuBorderHover"] = "#c0ffffff";
        style["textColor"]            = "#f0f0f0";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#ffffff";
        style["iconColor"]            = "#e0e0e0";
        style["iconHoverColor"]       = "#ffffff";
        style["submenuAccent"]        = "#ffffff";
        style["centerColor"]          = "#30ffffff";
        style["centerBorder"]         = "#50ffffff";
        style["centerBorderHover"]    = "#ffffff";
        style["centerDotColor"]       = "#ffffff";
        style["centerDotHoverColor"]  = "#ffffff";
        style["guideRingColor"]       = "#ffffff";
        style["guideRingOpacity"]     = 0.15;
        style["breadcrumbColor"]      = "#cccccc";
    } else if (name == "apple-glass" || name == "apple" || name == "apple-dark" || name == "macos-glass") {
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0; // Transparent backdrop so only pills blur
        style["pillColor"]            = "#55202026"; // translucent smoky acrylic glass
        style["pillHoverColor"]       = "#7532323c";
        style["pillBorderColor"]      = "#35ffffff"; // fine specular rim
        style["pillBorderHoverColor"] = "#85ffffff";
        style["pillSubmenuColor"]     = "#551e1e2c";
        style["pillSubmenuHoverColor"]= "#752c2c42";
        style["pillSubmenuBorder"]    = "#458282ff";
        style["pillSubmenuBorderHover"] = "#90a0a0ff";
        style["textColor"]            = "#f5f5f7";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#0a84ff"; // Apple System Blue
        style["iconColor"]            = "#ebebf5";
        style["iconHoverColor"]       = "#0a84ff";
        style["submenuAccent"]        = "#bf5af2"; // Apple System Purple
        style["centerColor"]          = "#55202026";
        style["centerBorder"]         = "#45ffffff";
        style["centerBorderHover"]    = "#0a84ff";
        style["centerDotColor"]       = "#ebebf5";
        style["centerDotHoverColor"]  = "#0a84ff";
        style["guideRingColor"]       = "#ffffff";
        style["guideRingOpacity"]     = 0.08;
        style["breadcrumbColor"]      = "#86868b";
        style["fontFamily"]           = "SF Pro Display, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 44;
        style["pillRadius"]           = 22;
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "apple-glass-light" || name == "apple-light" || name == "macos-light") {
        style["backgroundColor"]      = "#ffffff";
        style["backgroundOpacity"]    = 0.0; // Transparent backdrop
        style["pillColor"]            = "#8fffffff"; // frosted translucent white
        style["pillHoverColor"]       = "#c8ffffff";
        style["pillBorderColor"]      = "#55ffffff";
        style["pillBorderHoverColor"] = "#0071e3"; // Apple Vibrant Blue
        style["pillSubmenuColor"]     = "#88f2f2f7";
        style["pillSubmenuHoverColor"]= "#b8e5e5ea";
        style["pillSubmenuBorder"]    = "#55d1d1d6";
        style["pillSubmenuBorderHover"] = "#5856d6";
        style["textColor"]            = "#1d1d1f";
        style["textHoverColor"]       = "#000000";
        style["accentColor"]          = "#0071e3";
        style["iconColor"]            = "#424245";
        style["iconHoverColor"]       = "#0071e3";
        style["submenuAccent"]        = "#5856d6";
        style["centerColor"]          = "#99ffffff";
        style["centerBorder"]         = "#50d1d1d6";
        style["centerBorderHover"]    = "#0071e3";
        style["centerDotColor"]       = "#1d1d1f";
        style["centerDotHoverColor"]  = "#0071e3";
        style["guideRingColor"]       = "#000000";
        style["guideRingOpacity"]     = 0.06;
        style["breadcrumbColor"]      = "#86868b";
        style["fontFamily"]           = "SF Pro Display, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 44;
        style["pillRadius"]           = 22;
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "visionos" || name == "vision-glass" || name == "vision") {
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0; // Transparent backdrop
        style["pillColor"]            = "#35ffffff"; // visionOS translucent frosted glass
        style["pillHoverColor"]       = "#58ffffff";
        style["pillBorderColor"]      = "#45ffffff";
        style["pillBorderHoverColor"] = "#b5ffffff";
        style["pillSubmenuColor"]     = "#2cffffff";
        style["pillSubmenuHoverColor"]= "#4cffffff";
        style["pillSubmenuBorder"]    = "#55ffffff";
        style["pillSubmenuBorderHover"] = "#64d2ff";
        style["textColor"]            = "#f5f5f7";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#64d2ff"; // visionOS Cyan / Ice Blue
        style["iconColor"]            = "#d1d1d6";
        style["iconHoverColor"]       = "#64d2ff";
        style["submenuAccent"]        = "#bf5af2";
        style["centerColor"]          = "#30ffffff";
        style["centerBorder"]         = "#50ffffff";
        style["centerBorderHover"]    = "#64d2ff";
        style["centerDotColor"]       = "#ffffff";
        style["centerDotHoverColor"]  = "#64d2ff";
        style["guideRingColor"]       = "#64d2ff";
        style["guideRingOpacity"]     = 0.08;
        style["breadcrumbColor"]      = "#8e8e93";
        style["fontFamily"]           = "SF Pro Display, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 44;
        style["pillRadius"]           = 14; // soft squircle rounded corners
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "apple-glass-pie" || name == "apple-pie") {
        style["layout"]               = "pie";
        style["centerLayout"]         = "torus";
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0;
        style["pieBackgroundColor"]   = "#40121218";
        style["pieBackgroundOpacity"] = 1.0;
        style["pieOuterBorderColor"]  = "#40ffffff";
        style["pieOuterBorderWidth"]  = 1;
        style["innerRadius"]          = 55;
        style["outerRadius"]          = 225;
        style["delimiterWidth"]       = 1;
        style["delimiterColor"]       = "#30ffffff";
        style["pieSliceColor"]        = "#25ffffff";
        style["pieSliceHoverColor"]   = "#48ffffff";
        style["pieSliceSubmenuColor"] = "#25ffffff";
        style["pieSliceSubmenuHoverColor"] = "#48ffffff";
        style["highlightOptionRect"]  = true;
        style["optionRectColor"]       = "#30ffffff";
        style["optionRectHoverColor"] = "#600a84ff";
        style["optionRectBorder"]     = "#45ffffff";
        style["optionRectHoverBorder"]= "#0a84ff";
        style["optionRectRadius"]     = 12;
        style["accentColor"]          = "#0a84ff";
        style["submenuAccent"]        = "#bf5af2";
        style["textColor"]            = "#f5f5f7";
        style["textHoverColor"]       = "#ffffff";
        style["fontSize"]             = 14;
        style["iconSize"]             = 22;
        style["torusRadius"]          = 28;
        style["centerTorusThickness"] = 6;
        style["centerTorusColor"]     = "#40ffffff";
        style["showCenterArc"]        = true;
        style["centerArcAngle"]       = 90;
        style["centerArcColor"]       = "#0a84ff";
        style["centerArcWidth"]       = 6;
        style["centerColor"]          = "transparent";
        style["centerBorderColor"]     = "transparent";
        style["centerBorderHoverColor"]= "transparent";
        style["centerBorderWidth"]    = 0;
        style["centerDotColor"]       = "#ffffff";
        style["centerDotHoverColor"]  = "#0a84ff";
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "apple-lens" || name == "apple-optical" || name == "lens-dark") {
        style["useScreencopyGlass"]   = true;
        style["screencopyBlurRadius"] = 7;
        style["screencopyVibrancy"]   = 1.35;
        style["chromaticAberration"]  = 5;
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0;
        style["pillColor"]            = "#501c1c24"; // translucent smoky acrylic tint
        style["pillHoverColor"]       = "#702e2e3a";
        style["pillBorderColor"]      = "#45ffffff"; // crisp specular rim
        style["pillBorderHoverColor"] = "#95ffffff";
        style["pillSubmenuColor"]     = "#501a1a2a";
        style["pillSubmenuHoverColor"]= "#702a2a3e";
        style["pillSubmenuBorder"]    = "#458282ff";
        style["pillSubmenuBorderHover"] = "#90a0a0ff";
        style["textColor"]            = "#f5f5f7";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#0a84ff";
        style["iconColor"]            = "#ebebf5";
        style["iconHoverColor"]       = "#0a84ff";
        style["submenuAccent"]        = "#bf5af2";
        style["centerColor"]          = "#501c1c24";
        style["centerBorder"]         = "#45ffffff";
        style["centerBorderHover"]    = "#0a84ff";
        style["centerDotColor"]       = "#ebebf5";
        style["centerDotHoverColor"]  = "#0a84ff";
        style["fontFamily"]           = "SF Pro Display, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 44;
        style["pillRadius"]           = 22;
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "apple-lens-light" || name == "lens-light") {
        style["useScreencopyGlass"]   = true;
        style["screencopyBlurRadius"] = 7;
        style["screencopyVibrancy"]   = 1.20;
        style["backgroundColor"]      = "#ffffff";
        style["backgroundOpacity"]    = 0.0;
        style["pillColor"]            = "#75ffffff"; // translucent milk glass
        style["pillHoverColor"]       = "#a5ffffff";
        style["pillBorderColor"]      = "#60ffffff";
        style["pillBorderHoverColor"] = "#0071e3";
        style["pillSubmenuColor"]     = "#75f2f2f7";
        style["pillSubmenuHoverColor"]= "#a5e5e5ea";
        style["pillSubmenuBorder"]    = "#55d1d1d6";
        style["pillSubmenuBorderHover"] = "#5856d6";
        style["textColor"]            = "#1d1d1f";
        style["textHoverColor"]       = "#000000";
        style["accentColor"]          = "#0071e3";
        style["iconColor"]            = "#424245";
        style["iconHoverColor"]       = "#0071e3";
        style["submenuAccent"]        = "#5856d6";
        style["centerColor"]          = "#80ffffff";
        style["centerBorder"]         = "#50d1d1d6";
        style["centerBorderHover"]    = "#0071e3";
        style["centerDotColor"]       = "#1d1d1f";
        style["centerDotHoverColor"]  = "#0071e3";
        style["fontFamily"]           = "SF Pro Display, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 44;
        style["pillRadius"]           = 22;
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "visionos-lens" || name == "vision-lens") {
        style["useScreencopyGlass"]   = true;
        style["screencopyBlurRadius"] = 8;
        style["screencopyVibrancy"]   = 1.40;
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0;
        style["pillColor"]            = "#35ffffff";
        style["pillHoverColor"]       = "#58ffffff";
        style["pillBorderColor"]      = "#45ffffff";
        style["pillBorderHoverColor"] = "#b5ffffff";
        style["pillSubmenuColor"]     = "#2cffffff";
        style["pillSubmenuHoverColor"]= "#4cffffff";
        style["pillSubmenuBorder"]    = "#55ffffff";
        style["pillSubmenuBorderHover"] = "#64d2ff";
        style["textColor"]            = "#f5f5f7";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#64d2ff";
        style["iconColor"]            = "#d1d1d6";
        style["iconHoverColor"]       = "#64d2ff";
        style["submenuAccent"]        = "#bf5af2";
        style["centerColor"]          = "#30ffffff";
        style["centerBorder"]         = "#50ffffff";
        style["centerBorderHover"]    = "#64d2ff";
        style["centerDotColor"]       = "#ffffff";
        style["centerDotHoverColor"]  = "#64d2ff";
        style["fontFamily"]           = "SF Pro Display, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 44;
        style["pillRadius"]           = 14; // squircle
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "liquid-glass" || name == "apple-liquid" || name == "liquid" || name == "liquid-dark") {
        style["useScreencopyGlass"]   = true;
        style["screencopyBlurRadius"] = 7;
        style["screencopyVibrancy"]   = 1.45; // Enhanced WWDC 2025/2026 Liquid Glass vibrancy
        style["chromaticAberration"]  = 6;    // Enhanced 2D Liquid Chromatic Prism Dispersion
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.0;
        style["pillColor"]            = "#4214141c"; // Fluid deep liquid tint
        style["pillHoverColor"]       = "#68252535";
        style["pillBorderColor"]      = "#55ffffff"; // Multi-stage crystalline rim
        style["pillBorderHoverColor"] = "#b0ffffff";
        style["pillSubmenuColor"]     = "#42181426";
        style["pillSubmenuHoverColor"]= "#682a2240";
        style["pillSubmenuBorder"]    = "#55bf5af2";
        style["pillSubmenuBorderHover"] = "#b0df8aff";
        style["textColor"]            = "#f5f5f7";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#0a84ff"; // Liquid Electric Blue
        style["iconColor"]            = "#ebebf5";
        style["iconHoverColor"]       = "#0a84ff";
        style["submenuAccent"]        = "#ff375f"; // Liquid Rose / Magenta
        style["centerColor"]          = "#4214141c";
        style["centerBorder"]         = "#55ffffff";
        style["centerBorderHover"]    = "#0a84ff";
        style["centerDotColor"]       = "#ebebf5";
        style["centerDotHoverColor"]  = "#0a84ff";
        style["fontFamily"]           = "SF Pro Display, -apple-system, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 46;
        style["pillRadius"]           = 18; // Smooth liquid squircle
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "liquid-glass-light" || name == "liquid-light") {
        style["useScreencopyGlass"]   = true;
        style["screencopyBlurRadius"] = 7;
        style["screencopyVibrancy"]   = 1.25;
        style["backgroundColor"]      = "#ffffff";
        style["backgroundOpacity"]    = 0.0;
        style["pillColor"]            = "#75fcfcfd"; // Fluid milky light glass
        style["pillHoverColor"]       = "#b5ffffff";
        style["pillBorderColor"]      = "#70ffffff";
        style["pillBorderHoverColor"] = "#0071e3";
        style["pillSubmenuColor"]     = "#75f5f3f9";
        style["pillSubmenuHoverColor"]= "#b5ebe6f7";
        style["pillSubmenuBorder"]    = "#65bf5af2";
        style["pillSubmenuBorderHover"] = "#5856d6";
        style["textColor"]            = "#1d1d1f";
        style["textHoverColor"]       = "#000000";
        style["accentColor"]          = "#0071e3";
        style["iconColor"]            = "#3a3a3c";
        style["iconHoverColor"]       = "#0071e3";
        style["submenuAccent"]        = "#ff2d55";
        style["centerColor"]          = "#80ffffff";
        style["centerBorder"]         = "#60d1d1d6";
        style["centerBorderHover"]    = "#0071e3";
        style["centerDotColor"]       = "#1d1d1f";
        style["centerDotHoverColor"]  = "#0071e3";
        style["fontFamily"]           = "SF Pro Display, -apple-system, Inter, Cantarell, Sans";
        style["fontSize"]             = 13;
        style["pillHeight"]           = 46;
        style["pillRadius"]           = 18;
        style["borderWidth"]          = 1;
        style["borderHoverWidth"]     = 2;
        style["showGuideRing"]        = false;
        style["showPointerLine"]      = false;
    } else if (name == "monochrome") {
        style["backgroundColor"]      = "#000000";
        style["backgroundOpacity"]    = 0.40;
        style["pillColor"]            = "#111111";
        style["pillHoverColor"]       = "#222222";
        style["pillBorderColor"]      = "#333333";
        style["pillBorderHoverColor"] = "#ffffff";
        style["pillSubmenuColor"]     = "#111111";
        style["pillSubmenuHoverColor"]= "#222222";
        style["pillSubmenuBorder"]    = "#555555";
        style["pillSubmenuBorderHover"] = "#ffffff";
        style["textColor"]            = "#aaaaaa";
        style["textHoverColor"]       = "#ffffff";
        style["accentColor"]          = "#ffffff";
        style["iconColor"]            = "#aaaaaa";
        style["iconHoverColor"]       = "#ffffff";
        style["submenuAccent"]        = "#ffffff";
        style["centerColor"]          = "#111111";
        style["centerBorder"]         = "#333333";
        style["centerBorderHover"]    = "#ffffff";
        style["centerDotColor"]       = "#888888";
        style["centerDotHoverColor"]  = "#ffffff";
        style["guideRingColor"]       = "#ffffff";
        style["guideRingOpacity"]     = 0.08;
        style["breadcrumbColor"]      = "#888888";
    } else if (name == "light") {
        style["backgroundColor"]      = "#ffffff";
        style["backgroundOpacity"]    = 0.30;
        style["pillColor"]            = "#f0f0f3";
        style["pillHoverColor"]       = "#e4e4e9";
        style["pillBorderColor"]      = "#d0d0d8";
        style["pillBorderHoverColor"] = "#2563eb";
        style["pillSubmenuColor"]     = "#f5f3ff";
        style["pillSubmenuHoverColor"]= "#ede9fe";
        style["pillSubmenuBorder"]    = "#ddd6fe";
        style["pillSubmenuBorderHover"] = "#7c3aed";
        style["textColor"]            = "#1f2937";
        style["textHoverColor"]       = "#000000";
        style["accentColor"]          = "#2563eb";
        style["iconColor"]            = "#4b5563";
        style["iconHoverColor"]       = "#2563eb";
        style["submenuAccent"]        = "#7c3aed";
        style["centerColor"]          = "#ffffff";
        style["centerBorder"]         = "#d0d0d8";
        style["centerBorderHover"]    = "#2563eb";
        style["centerDotColor"]       = "#6b7280";
        style["centerDotHoverColor"]  = "#2563eb";
        style["guideRingColor"]       = "#000000";
        style["guideRingOpacity"]     = 0.08;
        style["breadcrumbColor"]      = "#4b5563";
    }

    // Apply custom overrides on top of resolved preset
    for (auto it = customOverrides.cbegin(); it != customOverrides.cend(); ++it) {
        style[it.key()] = it.value();
    }

    return style;
}
